mkdir -p ~/.config/hypr/scripts
nano ~/.config/hypr/scripts/wallpaper-slideshow.sh




#!/bin/bash

DIR="$HOME/Pictures/Wallpapers"
MONITOR="$(hyprctl monitors -j | jq -r '.[0].name')"  # first monitor

while true; do
    WALLPAPER="$(find "$DIR" -maxdepth 1 -type f ( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' ) | shuf -n 1)"
    [ -z "$WALLPAPER" ] && sleep 60 && continue

    # tell hyprpaper to use this image
    hyprctl hyprpaper preload "$WALLPAPER"
    hyprctl hyprpaper wallpaper "$MONITOR,$WALLPAPER"

    # change every 10 minutes (600 seconds) – adjust as you like
    sleep 600
done








chmod +x ~/.config/hypr/scripts/wallpaper-slideshow.sh






sudo pacman -S jq






nano ~/.config/hypr/hyprland.conf




exec-once = hyprpaper
exec-once = ~/.config/hypr/scripts/wallpaper-slideshow.sh







